--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 2025.2.37.0
-- Product home page: https://www.devart.com/dbforge/sql/studio
-- Script date 07.10.2025 7:57:39
-- Server version: 16.00.1000
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT EmployeeDB.dbo.Employees ON
GO
INSERT EmployeeDB.dbo.Employees(EmployeeID, FirstName, LastName, Email, DateOfBirth, Salary) VALUES (1, N'地地地地', N'上上上上上上上', N'аааю', NULL, 26)
INSERT EmployeeDB.dbo.Employees(EmployeeID, FirstName, LastName, Email, DateOfBirth, Salary) VALUES (2, N'土山千', N'土山千', N'土山千@e.j', '1982-11-11', 999)
INSERT EmployeeDB.dbo.Employees(EmployeeID, FirstName, LastName, Email, DateOfBirth, Salary) VALUES (4, N'千千千千', N'eeeee', N'eeeee@gmail.com', '1999-11-11', 111)
INSERT EmployeeDB.dbo.Employees(EmployeeID, FirstName, LastName, Email, DateOfBirth, Salary) VALUES (5, N'abcd', N'abcd', N'', NULL, NULL)
INSERT EmployeeDB.dbo.Employees(EmployeeID, FirstName, LastName, Email, DateOfBirth, Salary) VALUES (6, N'Сергей', N'Иванов', N'', NULL, 999)
INSERT EmployeeDB.dbo.Employees(EmployeeID, FirstName, LastName, Email, DateOfBirth, Salary) VALUES (7, N'Аркадий', N'Петров', N'', NULL, 2)
INSERT EmployeeDB.dbo.Employees(EmployeeID, FirstName, LastName, Email, DateOfBirth, Salary) VALUES (8, N'Василий', N'・', N'vas@gmail.ru', '2021-02-23', 3)
INSERT EmployeeDB.dbo.Employees(EmployeeID, FirstName, LastName, Email, DateOfBirth, Salary) VALUES (9, N'・', N'・', N'', NULL, 999)
INSERT EmployeeDB.dbo.Employees(EmployeeID, FirstName, LastName, Email, DateOfBirth, Salary) VALUES (10, N'Grzegorz ', N'Szcząść', N'Grzegorz@gmail.com', NULL, 999)
INSERT EmployeeDB.dbo.Employees(EmployeeID, FirstName, LastName, Email, DateOfBirth, Salary) VALUES (11, N'上学@在外地', N'在外地上学', N'在外地上学@gmail.com', '2001-11-25', NULL)
INSERT EmployeeDB.dbo.Employees(EmployeeID, FirstName, LastName, Email, DateOfBirth, Salary) VALUES (12, N'Przęślęźlińśćń', N'Żźdźbłłęściń', N'Żźdźbłłęściń@xxx.xxx', '1982-11-04', 111)
INSERT EmployeeDB.dbo.Employees(EmployeeID, FirstName, LastName, Email, DateOfBirth, Salary) VALUES (13, N'��', N'��', N'��@hhh.rrr', '1111-11-11', 999)
INSERT EmployeeDB.dbo.Employees(EmployeeID, FirstName, LastName, Email, DateOfBirth, Salary) VALUES (14, N'true地上学', N'地上学', N'地上学@ss.ss', '1982-11-01', 999)
GO
SET IDENTITY_INSERT EmployeeDB.dbo.Employees OFF
GO